/* beken_ui.h — auto-generated by android2lvgl */
#ifndef __BEKEN_UI_H__
#define __BEKEN_UI_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "ui_config.h"
// #include "main_activity.h"


#define SCREEN_WIDTH  1024
#define SCREEN_HEIGHT 600

/* ── 팝업 배경 불투명 모드 ─────────────────────────────────────────────
 * 1: 팝업 배경을 불투명 단색으로 렌더 (roller 동작 빠름)
 *    - dirty area마다 active screen JPEG 재합성 스킵 → SW alpha blend 제거
 *    - 시각: 뒷배경이 비치지 않는 어두운 단색 배경
 * 0: 기존 60% 반투명 오버레이 (느리지만 뒷배경 비침)                   */
#define POPUP_OPAQUE_BG  0

/* Font declarations */
extern lv_font_t lv_font_montserrat_regular_16;
extern lv_font_t lv_font_scdream_regular_22;
extern lv_font_t lv_font_scdream_regular_26;
extern lv_font_t lv_font_scdream_regular_32;
extern lv_font_t lv_font_scdream_regular_33;
extern lv_font_t lv_font_scdream_regular_35;
extern lv_font_t lv_font_scdream_regular_40;
extern lv_font_t lv_font_scdream_regular_42;
extern lv_font_t lv_font_scdream_regular_49;
extern lv_font_t lv_font_scdream_regular_66;
/* 중국어 ON/OFF(开/关) 전용 최소 폰트 — lv_font_scdream_regular_*에는 CJK
 * 글리프가 없어 별도 생성 (fonts/lv_font_onoff_cn_32/72/90.c).
 * _32: 설정값 표시 라벨(txts[]), _72/_90: roller MAIN/SELECTED 폰트와 동일 크기 */
extern lv_font_t lv_font_onoff_cn_32;
extern lv_font_t lv_font_onoff_cn_72;
extern lv_font_t lv_font_onoff_cn_90;


extern lv_font_t lv_font_scdream_regular_72;

extern lv_font_t lv_font_scdream_regular_90;


typedef struct {
    /* Page: 0 - activitymain */
    lv_obj_t *activitymain;
    lv_obj_t *activitymain_bg;

    /* Page: 1 - autodrymode */
    lv_obj_t *autodrymode;
    lv_obj_t *autodrymode_bg;
    lv_obj_t *autodrymode_title;
    lv_obj_t *autodrymode_backbt;
    lv_obj_t *autodrymode_backim;
    lv_obj_t *autodrymode_auto_dry_circle_basic;
    lv_obj_t *autodrymode_auto_dry_circle_gif;
    lv_obj_t *autodrymode_auto_dry_txt_basic;
    lv_obj_t *autodrymode_auto_dry_gif;
    lv_obj_t *autodrymode_auto_dry_gif_basic;
    lv_obj_t *autodrymode_auto_dry_temp_txt;
    lv_obj_t *autodrymode_auto_dry_humidity_txt;
    lv_obj_t *autodrymode_auto_dry_temp_underbar;
    lv_obj_t *autodrymode_auto_dry_humidity_underbar;
    lv_obj_t *autodrymode_auto_dry_temp_bt;
    lv_obj_t *autodrymode_auto_dry_humidity_bt;
    lv_obj_t *autodrymode_test_circle_line;
    lv_obj_t *autodrymode_imageview16;
    lv_obj_t *autodrymode_auto_dry_hour_txt;
    lv_obj_t *autodrymode_auto_dry_hour_underbar;
    lv_obj_t *autodrymode_auto_dry_hour_bt;
    lv_obj_t *autodrymode_auto_dry_min_txt;
    lv_obj_t *autodrymode_auto_dry_min_underbar;
    lv_obj_t *autodrymode_auto_dry_min_bt;
    lv_obj_t *autodrymode_auto_tempbox;
    lv_obj_t *autodrymode_tempbox_current_temp;
    lv_obj_t *autodrymode_tempbox_current_humidity;
    lv_obj_t *autodrymode_auto_dry_start;
    lv_obj_t *autodrymode_auto_dry_startim;
    lv_obj_t *autodrymode_keypadbaseim;
    lv_obj_t *autodrymode_keypad1;
    lv_obj_t *autodrymode_keypad1_im;
    lv_obj_t *autodrymode_keypad2;
    lv_obj_t *autodrymode_keypad2_im;
    lv_obj_t *autodrymode_keypad3;
    lv_obj_t *autodrymode_keypad3_im;
    lv_obj_t *autodrymode_keypad4;
    lv_obj_t *autodrymode_keypad4_im;
    lv_obj_t *autodrymode_keypad5;
    lv_obj_t *autodrymode_keypad5_im;
    lv_obj_t *autodrymode_keypad6;
    lv_obj_t *autodrymode_keypad6_im;
    lv_obj_t *autodrymode_keypad7;
    lv_obj_t *autodrymode_keypad7_im;
    lv_obj_t *autodrymode_keypad8;
    lv_obj_t *autodrymode_keypad8_im;
    lv_obj_t *autodrymode_keypad9;
    lv_obj_t *autodrymode_keypad9_im;
    lv_obj_t *autodrymode_keypad0;
    lv_obj_t *autodrymode_keypad0_im;
    lv_obj_t *autodrymode_keypadminor;
    lv_obj_t *autodrymode_keypadminor_im;
    lv_obj_t *autodrymode_keypadbackspace;
    lv_obj_t *autodrymode_keypadbackspace_im;
    lv_obj_t *autodrymode_keypadhide;
    lv_obj_t *autodrymode_keypadhide_im;
    lv_obj_t *autodrymode_blackout;
    lv_obj_t *autodrymode_run_arc;
    lv_obj_t *autodrymode_run_arc_bg_white;
    lv_obj_t *autodrymode_KeyPadBt[12];
    lv_obj_t *autodrymode_KeyPadIm[12];

    /* Page: 4 - automodeend */
    lv_obj_t *automodeend;
    lv_obj_t *automodeend_auto_mode_end_bg;
    lv_obj_t *automodeend_auto_mode_end_overtime;
    lv_obj_t *automodeend_title;
    lv_obj_t *automodeend_stopbt;
    lv_obj_t *automodeend_imageview5;
    lv_obj_t *automodeend_AutoModeCompleteYear;
    lv_obj_t *automodeend_AutoModeCompleteMonth;
    lv_obj_t *automodeend_AutoModeCompleteDay;
    lv_obj_t *automodeend_AutoModeCompleteHour;
    lv_obj_t *automodeend_AutoModeCompleteMin;
    lv_obj_t *automodeend_blackout;

    /* Page: 7 - automode */
    lv_obj_t *automode;
    lv_obj_t *automode_bg;
    lv_obj_t *automode_title;
    lv_obj_t *automode_backbt;
    lv_obj_t *automode_imageview3;
    lv_obj_t *automode_startbt;
    lv_obj_t *automode_imageview5;
    lv_obj_t *automode_imageview6;
    lv_obj_t *automode_AutoModeCompleteYear;
    lv_obj_t *automode_AutoModeCompleteYearBt;
    // lv_obj_t *automode_AutoModeCompleteYearTxt;
    // lv_obj_t *automode_AutoModeCompleteMonthTxt;
    // lv_obj_t *automode_AutoModeCompleteDayTxt;
    // lv_obj_t *automode_AutoModeCompleteHourTxt;
    // lv_obj_t *automode_AutoModeCompleteMinTxt;

    lv_obj_t *automode_AutoModeCompleteYearUnderBarIm;
    lv_obj_t *automode_AutoModeCompleteMonth;
    lv_obj_t *automode_AutoModeCompleteMonthBt;
    lv_obj_t *automode_AutoModeCompleteMonthUnderBarIm;
    lv_obj_t *automode_AutoModeCompleteDay;
    lv_obj_t *automode_AutoModeCompleteDayBt;
    lv_obj_t *automode_AutoModeCompleteDayUnderBarIm;
    lv_obj_t *automode_AutoModeCompleteHour;
    lv_obj_t *automode_AutoModeCompleteHourBt;
    lv_obj_t *automode_AutoModeCompleteHourUnderBarIm;
    lv_obj_t *automode_AutoModeCompleteMin;
    lv_obj_t *automode_AutoModeCompleteMinBt;
    lv_obj_t *automode_AutoModeCompleteMinUnderBarIm;
    lv_obj_t *automode_loadbt;
    lv_obj_t *automode_imageview23;
    lv_obj_t *automode_savebt;
    lv_obj_t *automode_imageview25;
    lv_obj_t *automode_imageview26;
    lv_obj_t *automode_AutoFreezeTempBt;
    lv_obj_t *automode_AutoFreezeTempTxt;
    lv_obj_t *automode_AutoModeFreezeTempUnderBarIm;
    lv_obj_t *automode_AutoModeFreezeTempCheckBoxIm;
    lv_obj_t *automode_imageview31;
    lv_obj_t *automode_AutoDefrostTempBt;
    lv_obj_t *automode_AutoDefrostTempTxt;
    lv_obj_t *automode_AutoModeDefrostTempUnderBarIm;
    lv_obj_t *automode_AutoModeDefrostTempCheckBoxIm;
    lv_obj_t *automode_AutoDefrostTimeHourBt;
    lv_obj_t *automode_AutoDefrostTimeHourTxt;
    lv_obj_t *automode_AutoModeDefrostTimeHourUnderBarIm;
    lv_obj_t *automode_AutoDefrostTimeMinBt;
    lv_obj_t *automode_AutoDefrostTimeMinTxt;
    lv_obj_t *automode_AutoModeDefrostTimeMinUnderBarIm;
    lv_obj_t *automode_AutoModeDefrostTimeCheckBoxIm;
    lv_obj_t *automode_AutoModeDefrostAutoTime;
    lv_obj_t *automode_imageview44;
    lv_obj_t *automode_AutoFermentation1TempBt;
    lv_obj_t *automode_AutoFermentation1TempTxt;
    lv_obj_t *automode_AutoModeFermentation1TempUnderBarIm;
    lv_obj_t *automode_AutoModeFermentation1TempCheckBoxIm;
    lv_obj_t *automode_AutoFermentation1HumidityBt;
    lv_obj_t *automode_AutoFermentation1HumidityTxt;
    lv_obj_t *automode_AutoModeFermentation1HumidityUnderBarIm;
    lv_obj_t *automode_AutoModeFermentation1HumidityCheckBoxIm;
    lv_obj_t *automode_AutoFermentation1TimeHourBt;
    lv_obj_t *automode_AutoFermentation1TimeHourTxt;
    lv_obj_t *automode_AutoModeFermentation1TimeHourUnderBarIm;
    lv_obj_t *automode_AutoFermentation1TimeMinBt;
    lv_obj_t *automode_AutoFermentation1TimeMinTxt;
    lv_obj_t *automode_AutoModeFermentation1TimeMinUnderBarIm;
    lv_obj_t *automode_AutoModeFermentation1TimeCheckBoxIm;
    lv_obj_t *automode_imageview60;
    lv_obj_t *automode_AutoFermentation2TempBt;
    lv_obj_t *automode_AutoFermentation2TempTxt;
    lv_obj_t *automode_AutoModeFermentation2TempUnderBarIm;
    lv_obj_t *automode_AutoModeFermentation2TempCheckBoxIm;
    lv_obj_t *automode_AutoFermentation2HumidityBt;
    lv_obj_t *automode_AutoFermentation2HumidityTxt;
    lv_obj_t *automode_AutoModeFermentation2HumidityUnderBarIm;
    lv_obj_t *automode_AutoModeFermentation2HumidityCheckBoxIm;
    lv_obj_t *automode_AutoFermentation2TimeHourBt;
    lv_obj_t *automode_AutoFermentation2TimeHourTxt;
    lv_obj_t *automode_AutoModeFermentation2TimeHourUnderBarIm;
    lv_obj_t *automode_AutoFermentation2TimeMinBt;
    lv_obj_t *automode_AutoFermentation2TimeMinTxt;
    lv_obj_t *automode_AutoModeFermentation2TimeMinUnderBarIm;
    lv_obj_t *automode_AutoModeFermentation2TimeCheckBoxIm;
    lv_obj_t *automode_keypadbaseim;
    lv_obj_t *automode_KeyPadBt[12];
    lv_obj_t *automode_KeyPadIm[12];
    lv_obj_t *automode_keypadhide;
    lv_obj_t *automode_keypadhide_im;
    lv_obj_t *automode_auto_f1;
    lv_obj_t *automode_auto_f2;
    lv_obj_t *automode_auto_f3;
    lv_obj_t *automode_auto_f4;

    /* Page: 10 - automodestart */
    lv_obj_t *automodestart;
    lv_obj_t *automodestart_auto_bg;
    lv_obj_t *automodestart_title;
    lv_obj_t *automodestart_AutoFreezeIm;
    lv_obj_t *automodestart_AutoDefrostIm;
    lv_obj_t *automodestart_AutoFermentation1Im;
    lv_obj_t *automodestart_AutoFermentation2Im;
    lv_obj_t *automodestart_freeze_arc;
    lv_obj_t *automodestart_defrost_arc;
    lv_obj_t *automodestart_ferm1_arc;
    lv_obj_t *automodestart_ferm2_arc;
    lv_obj_t *automodestart_startbt;
    lv_obj_t *automodestart_imageview8;
    lv_obj_t *automodestart_auto_tempbox;
    lv_obj_t *automodestart_tempbox_current_temp;
    lv_obj_t *automodestart_tempbox_current_humidity;
    lv_obj_t *automodestart_imageview12;
    lv_obj_t *automodestart_AutoModeCompleteYear;
    lv_obj_t *automodestart_AutoModeCompleteMonth;
    lv_obj_t *automodestart_AutoModeCompleteDay;
    lv_obj_t *automodestart_AutoModeCompleteHour;
    lv_obj_t *automodestart_AutoModeCompleteMin;
    lv_obj_t *automodestart_AutoFreezeTempTxt;
    lv_obj_t *automodestart_AutoFreezeTimeHourTxt;
    lv_obj_t *automodestart_AutoFreezeTimeMinTxt;
    lv_obj_t *automodestart_freeze_gif;
    lv_obj_t *automodestart_freeze_gif_basic;
    lv_obj_t *automodestart_defrost_gif;
    lv_obj_t *automodestart_defrost_gif_basic;
    lv_obj_t *automodestart_fermentation1_gif;
    lv_obj_t *automodestart_fermentation1_gif_basic;
    lv_obj_t *automodestart_fermentation2_gif;
    lv_obj_t *automodestart_fermentation2_gif_basic;
    lv_obj_t *automodestart_AutoDefrostTempTxt;
    lv_obj_t *automodestart_AutoDefrostTimeHourTxt;
    lv_obj_t *automodestart_AutoDefrostTimeMinTxt;
    lv_obj_t *automodestart_AutoFermentation2TempTxt;
    lv_obj_t *automodestart_AutoFermentation2HumidityTxt;
    lv_obj_t *automodestart_AutoFermentation2TimeHourTxt;
    lv_obj_t *automodestart_AutoFermentation2TimeMinTxt;
    lv_obj_t *automodestart_AutoFermentation1TempTxt;
    lv_obj_t *automodestart_AutoFermentation1HumidityTxt;
    lv_obj_t *automodestart_AutoFermentation1TimeHourTxt;
    lv_obj_t *automodestart_AutoFermentation1TimeMinTxt;
    lv_obj_t *automodestart_blackout;

    /* Page: 13 - detailsettingdamper */
    lv_obj_t *detailsettingdamper;
    lv_obj_t *detailsettingdamper_bg;
    lv_obj_t *detailsettingdamper_title;
    lv_obj_t *detailsettingdamper_backbt;
    lv_obj_t *detailsettingdamper_imageview3;
    lv_obj_t *detailsettingdamper_settingim1;
    lv_obj_t *detailsettingdamper_settingtxt1;
    lv_obj_t *detailsettingdamper_settingbt1;
    lv_obj_t *detailsettingdamper_settingim2;
    lv_obj_t *detailsettingdamper_settingtxt2;
    lv_obj_t *detailsettingdamper_settingbt2;
    lv_obj_t *detailsettingdamper_settingim3;
    lv_obj_t *detailsettingdamper_settingtxt3;
    lv_obj_t *detailsettingdamper_settingbt3;
    lv_obj_t *detailsettingdamper_settingim4;
    lv_obj_t *detailsettingdamper_settingtxt4;
    lv_obj_t *detailsettingdamper_settingbt4;
    lv_obj_t *detailsettingdamper_pickerbox;
    lv_obj_t *detailsettingdamper_settemp_setn1;
    lv_obj_t *detailsettingdamper_settemp_setn2;
    lv_obj_t *detailsettingdamper_settemp_setn3;
    lv_obj_t *detailsettingdamper_settemp_setn4;
    lv_obj_t *detailsettingdamper_imageview21;
    lv_obj_t *detailsettingdamper_changebt;

    /* Page: 16 - detailsettingdefrost */
    lv_obj_t *detailsettingdefrost;
    lv_obj_t *detailsettingdefrost_bg;
    lv_obj_t *detailsettingdefrost_title;
    lv_obj_t *detailsettingdefrost_backbt;
    lv_obj_t *detailsettingdefrost_imageview3;
    lv_obj_t *detailsettingdefrost_settingim1;
    lv_obj_t *detailsettingdefrost_settingtxt1;
    lv_obj_t *detailsettingdefrost_settingbt1;
    lv_obj_t *detailsettingdefrost_settingim2;
    lv_obj_t *detailsettingdefrost_settingtxt2;
    lv_obj_t *detailsettingdefrost_settingbt2;
    lv_obj_t *detailsettingdefrost_settingim3;
    lv_obj_t *detailsettingdefrost_settingtxt3;
    lv_obj_t *detailsettingdefrost_settingbt3;
    lv_obj_t *detailsettingdefrost_pickerbox;
    lv_obj_t *detailsettingdefrost_settemp_setn1;
    lv_obj_t *detailsettingdefrost_changebt;

    /* Page: 19 - detailsettinghumidity */
    lv_obj_t *detailsettinghumidity;
    lv_obj_t *detailsettinghumidity_bg;
    lv_obj_t *detailsettinghumidity_title;
    lv_obj_t *detailsettinghumidity_backbt;
    lv_obj_t *detailsettinghumidity_imageview3;
    lv_obj_t *detailsettinghumidity_settingim1;
    lv_obj_t *detailsettinghumidity_settingtxt1;
    lv_obj_t *detailsettinghumidity_settingbt1;
    lv_obj_t *detailsettinghumidity_settingim2;
    lv_obj_t *detailsettinghumidity_settingtxt2;
    lv_obj_t *detailsettinghumidity_settingbt2;
    lv_obj_t *detailsettinghumidity_settingim3;
    lv_obj_t *detailsettinghumidity_settingtxt3;
    lv_obj_t *detailsettinghumidity_settingbt3;
    lv_obj_t *detailsettinghumidity_pickerbox;
    lv_obj_t *detailsettinghumidity_settemp_setn1;
    lv_obj_t *detailsettinghumidity_changebt;

    /* Page: 22 - detailsettingtemp */
    lv_obj_t *detailsettingtemp;
    lv_obj_t *detailsettingtemp_bg;
    lv_obj_t *detailsettingtemp_title;
    lv_obj_t *detailsettingtemp_backbt;
    lv_obj_t *detailsettingtemp_imageview3;
    lv_obj_t *detailsettingtemp_settingim1;
    lv_obj_t *detailsettingtemp_settingtxt1;
    lv_obj_t *detailsettingtemp_settingbt1;
    lv_obj_t *detailsettingtemp_settingim2;
    lv_obj_t *detailsettingtemp_settingtxt2;
    lv_obj_t *detailsettingtemp_settingbt2;
    lv_obj_t *detailsettingtemp_settingim3;
    lv_obj_t *detailsettingtemp_settingtxt3;
    lv_obj_t *detailsettingtemp_settingbt3;
    lv_obj_t *detailsettingtemp_settingim4;
    lv_obj_t *detailsettingtemp_settingtxt4;
    lv_obj_t *detailsettingtemp_settingbt4;
    lv_obj_t *detailsettingtemp_imageview16;
    lv_obj_t *detailsettingtemp_leftbt;
    lv_obj_t *detailsettingtemp_currentpage;
    lv_obj_t *detailsettingtemp_imageview19;
    lv_obj_t *detailsettingtemp_rightbt;
    lv_obj_t *detailsettingtemp_pickerbox;
    lv_obj_t *detailsettingtemp_settemp_setn1;
    lv_obj_t *detailsettingtemp_changebt;

    /* Page: 25 - detailsettingtime */
    lv_obj_t *detailsettingtime;
    lv_obj_t *detailsettingtime_bg;
    lv_obj_t *detailsettingtime_title;
    lv_obj_t *detailsettingtime_backbt;
    lv_obj_t *detailsettingtime_imageview3;
    lv_obj_t *detailsettingtime_settingim1;
    lv_obj_t *detailsettingtime_settingtxt1_1;
    lv_obj_t *detailsettingtime_settingtxt1_2;
    lv_obj_t *detailsettingtime_settingbt1;
    lv_obj_t *detailsettingtime_settingim2;
    lv_obj_t *detailsettingtime_settingtxt2_1;
    lv_obj_t *detailsettingtime_settingtxt2_2;
    lv_obj_t *detailsettingtime_settingbt2;
    lv_obj_t *detailsettingtime_settingim3;
    lv_obj_t *detailsettingtime_settingtxt3;
    lv_obj_t *detailsettingtime_settingbt3;
    lv_obj_t *detailsettingtime_settingim4;
    lv_obj_t *detailsettingtime_settingtxt4;
    lv_obj_t *detailsettingtime_settingbt4;
    lv_obj_t *detailsettingtime_settingim5;
    lv_obj_t *detailsettingtime_settingtxt5;
    lv_obj_t *detailsettingtime_settingbt5;
    lv_obj_t *detailsettingtime_pickerbox;
    lv_obj_t *detailsettingtime_pickerbox2;
    lv_obj_t *detailsettingtime_settemp_setn1;
    lv_obj_t *detailsettingtime_settemp_setn2;
    lv_obj_t *detailsettingtime_settemp_setn3;
    lv_obj_t *detailsettingtime_settemp_setn4;
    lv_obj_t *detailsettingtime_settemp_setn5;
    lv_obj_t *detailsettingtime_settemp_setn6;
    lv_obj_t *detailsettingtime_settemp_setn7;
    lv_obj_t *detailsettingtime_changebt;

    /* Page: 28 - introactivity */
    lv_obj_t *introactivity;
    lv_obj_t *introactivity_intro;

    /* Page: 29 - main */
    lv_obj_t *main;
    lv_obj_t *main_bg;
    lv_obj_t *main_automode;
    lv_obj_t *main_imageview2;
    lv_obj_t *main_manualmode;
    lv_obj_t *main_imageview4;
    lv_obj_t *main_autodrymode;
    lv_obj_t *main_imageview6;
    lv_obj_t *main_memorymode;
    lv_obj_t *main_imageview8;
    lv_obj_t *main_settingmode;
    lv_obj_t *main_imageview10;
    lv_obj_t *main_timebar_date;  /* 날짜 표시 레이블  YYYY.MM.DD */
    lv_obj_t *main_dclock_1;      /* 시간 표시 레이블  HH:MM      */


    /* Page: 32 - manualmode */
    lv_obj_t *manualmode;
    lv_obj_t *manualmode_bg;
    lv_obj_t *manualmode_title;
    lv_obj_t *manualmode_backbt;
    lv_obj_t *manualmode_imageview3;
    lv_obj_t *manualmode_imageview4;
    lv_obj_t *manualmode_manual_freezebt;
    lv_obj_t *manualmode_manual_defrostbt;
    lv_obj_t *manualmode_manual_fermentationbt;

    /* Page: 35 - manualmodestart */
    lv_obj_t *manualmodestart;
    lv_obj_t *manualmodestart_bg;
    lv_obj_t *manualmodestart_title;
    lv_obj_t *manualmodestart_over_time_korea;
    lv_obj_t *manualmodestart_over_time_china;
    lv_obj_t *manualmodestart_over_time_english;
    lv_obj_t *manualmodestart_backbt;
    lv_obj_t *manualmodestart_backim;
    lv_obj_t *manualmodestart_startbt;
    lv_obj_t *manualmodestart_startim;
    lv_obj_t *manualmodestart_tempbox;
    lv_obj_t *manualmodestart_tempbox_current_temp;
    lv_obj_t *manualmodestart_tempbox_current_humidity;
    lv_obj_t *manualmodestart_manual_circle_basic;
    lv_obj_t *manualmodestart_manual_circle_gif;
    lv_obj_t *manualmodestart_manual_txt_basic;
    lv_obj_t *manualmodestart_manual_gif;
    lv_obj_t *manualmodestart_manual_gif_basic;
    lv_obj_t *manualmodestart_manual_freeze_temp_txt;
    lv_obj_t *manualmodestart_manual_defrost_temp_txt;
    lv_obj_t *manualmodestart_manual_fermentation_temp_txt;
    lv_obj_t *manualmodestart_manual_fermentation_humidity_txt;
    lv_obj_t *manualmodestart_manual_fermentation_temp_underbar;
    lv_obj_t *manualmodestart_manual_fermentation_humidity_underbar;
    lv_obj_t *manualmodestart_manual_freeze_temp_underbar;
    lv_obj_t *manualmodestart_manual_defrost_temp_underbar;
    lv_obj_t *manualmodestart_manual_freeze_temp_bt;
    lv_obj_t *manualmodestart_manual_defrost_temp_bt;
    lv_obj_t *manualmodestart_manual_fermentation_temp_bt;
    lv_obj_t *manualmodestart_manual_fermentation_humidity_bt;
    lv_obj_t *manualmodestart_test_circle_line;
    lv_obj_t *manualmodestart_keypadbaseim;
    lv_obj_t *manualmodestart_keypad1;
    lv_obj_t *manualmodestart_keypad1_im;
    lv_obj_t *manualmodestart_keypad2;
    lv_obj_t *manualmodestart_keypad2_im;
    lv_obj_t *manualmodestart_keypad3;
    lv_obj_t *manualmodestart_keypad3_im;
    lv_obj_t *manualmodestart_keypad4;
    lv_obj_t *manualmodestart_keypad4_im;
    lv_obj_t *manualmodestart_keypad5;
    lv_obj_t *manualmodestart_keypad5_im;
    lv_obj_t *manualmodestart_keypad6;
    lv_obj_t *manualmodestart_keypad6_im;
    lv_obj_t *manualmodestart_keypad7;
    lv_obj_t *manualmodestart_keypad7_im;
    lv_obj_t *manualmodestart_keypad8;
    lv_obj_t *manualmodestart_keypad8_im;
    lv_obj_t *manualmodestart_keypad9;
    lv_obj_t *manualmodestart_keypad9_im;
    lv_obj_t *manualmodestart_keypad0;
    lv_obj_t *manualmodestart_keypad0_im;
    lv_obj_t *manualmodestart_keypadminor;
    lv_obj_t *manualmodestart_keypadminor_im;
    lv_obj_t *manualmodestart_keypadbackspace;
    lv_obj_t *manualmodestart_keypadbackspace_im;
    lv_obj_t *manualmodestart_keypadhide;
    lv_obj_t *manualmodestart_keypadhide_im;
    lv_obj_t *manualmodestart_blackout;
    lv_obj_t *manualmodestart_run_arc;

    /* Page: 36 - memorymode */
    lv_obj_t *memorymode;
    lv_obj_t *memorymode_bg;
    lv_obj_t *memorymode_title;
    lv_obj_t *memorymode_backbt;
    lv_obj_t *memorymode_imageview3;
    lv_obj_t *memorymode_imageview4;
    lv_obj_t *memorymode_memorybox0;
    lv_obj_t *memorymode_memory_number0;
    lv_obj_t *memorymode_memory_Day_Period0;
    lv_obj_t *memorymode_memory_freeze_temp0;
    lv_obj_t *memorymode_memory_defrost_temp0;
    lv_obj_t *memorymode_memory_defrost_hour0;
    lv_obj_t *memorymode_memory_defrost_min0;
    lv_obj_t *memorymode_memory_fermentation1_temp0;
    lv_obj_t *memorymode_memory_fermentation1_humidity0;
    lv_obj_t *memorymode_memory_fermentation1_hour0;
    lv_obj_t *memorymode_memory_fermentation1_min0;
    lv_obj_t *memorymode_memory_fermentation2_temp0;
    lv_obj_t *memorymode_memory_fermentation2_humidity0;
    lv_obj_t *memorymode_memory_fermentation2_hour0;
    lv_obj_t *memorymode_memory_fermentation2_min0;
    lv_obj_t *memorymode_memory_completehour0;
    lv_obj_t *memorymode_memory_completemin0;
    lv_obj_t *memorymode_memory_check1im;
    lv_obj_t *memorymode_memory_check1bt;
    lv_obj_t *memorymode_memorybox1;
    lv_obj_t *memorymode_memory_number1;
    lv_obj_t *memorymode_memory_Day_Period1;
    lv_obj_t *memorymode_memory_freeze_temp1;
    lv_obj_t *memorymode_memory_defrost_temp1;
    lv_obj_t *memorymode_memory_defrost_hour1;
    lv_obj_t *memorymode_memory_defrost_min1;
    lv_obj_t *memorymode_memory_fermentation1_temp1;
    lv_obj_t *memorymode_memory_fermentation1_humidity1;
    lv_obj_t *memorymode_memory_fermentation1_hour1;
    lv_obj_t *memorymode_memory_fermentation1_min1;
    lv_obj_t *memorymode_memory_fermentation2_temp1;
    lv_obj_t *memorymode_memory_fermentation2_humidity1;
    lv_obj_t *memorymode_memory_fermentation2_hour1;
    lv_obj_t *memorymode_memory_fermentation2_min1;
    lv_obj_t *memorymode_memory_completehour1;
    lv_obj_t *memorymode_memory_completemin1;
    lv_obj_t *memorymode_memory_check2im;
    lv_obj_t *memorymode_memory_check2bt;
    lv_obj_t *memorymode_memorybox2;
    lv_obj_t *memorymode_memory_number2;
    lv_obj_t *memorymode_memory_Day_Period2;
    lv_obj_t *memorymode_memory_freeze_temp2;
    lv_obj_t *memorymode_memory_defrost_temp2;
    lv_obj_t *memorymode_memory_defrost_hour2;
    lv_obj_t *memorymode_memory_defrost_min2;
    lv_obj_t *memorymode_memory_fermentation1_temp2;
    lv_obj_t *memorymode_memory_fermentation1_humidity2;
    lv_obj_t *memorymode_memory_fermentation1_hour2;
    lv_obj_t *memorymode_memory_fermentation1_min2;
    lv_obj_t *memorymode_memory_fermentation2_temp2;
    lv_obj_t *memorymode_memory_fermentation2_humidity2;
    lv_obj_t *memorymode_memory_fermentation2_hour2;
    lv_obj_t *memorymode_memory_fermentation2_min2;
    lv_obj_t *memorymode_memory_completehour2;
    lv_obj_t *memorymode_memory_completemin2;
    lv_obj_t *memorymode_memory_check3im;
    lv_obj_t *memorymode_memory_check3bt;
    lv_obj_t *memorymode_memorybox3;
    lv_obj_t *memorymode_memory_number3;
    lv_obj_t *memorymode_memory_Day_Period3;
    lv_obj_t *memorymode_memory_freeze_temp3;
    lv_obj_t *memorymode_memory_defrost_temp3;
    lv_obj_t *memorymode_memory_defrost_hour3;
    lv_obj_t *memorymode_memory_defrost_min3;
    lv_obj_t *memorymode_memory_fermentation1_temp3;
    lv_obj_t *memorymode_memory_fermentation1_humidity3;
    lv_obj_t *memorymode_memory_fermentation1_hour3;
    lv_obj_t *memorymode_memory_fermentation1_min3;
    lv_obj_t *memorymode_memory_fermentation2_temp3;
    lv_obj_t *memorymode_memory_fermentation2_humidity3;
    lv_obj_t *memorymode_memory_fermentation2_hour3;
    lv_obj_t *memorymode_memory_fermentation2_min3;
    lv_obj_t *memorymode_memory_completehour3;
    lv_obj_t *memorymode_memory_completemin3;
    lv_obj_t *memorymode_memory_check4im;
    lv_obj_t *memorymode_memory_check4bt;
    lv_obj_t *memorymode_imageview81;
    lv_obj_t *memorymode_memoryleftbt;
    lv_obj_t *memorymode_memory1im;
    lv_obj_t *memorymode_memory1bt;
    lv_obj_t *memorymode_memory2im;
    lv_obj_t *memorymode_memory2bt;
    lv_obj_t *memorymode_memory3im;
    lv_obj_t *memorymode_memory3bt;
    lv_obj_t *memorymode_imageview89;
    lv_obj_t *memorymode_memoryrightbt;
    lv_obj_t *memorymode_okbt;
    lv_obj_t *memorymode_imageview92;
    lv_obj_t *memorymode_deleteim;
    lv_obj_t *memorymode_deletebt;

    /* Page: 39 - neurosys */
    lv_obj_t *neurosys;
    lv_obj_t *neurosys_allim;
    lv_obj_t *neurosys_allbt;
    lv_obj_t *neurosys_onebt;
    lv_obj_t *neurosys_twobt;
    lv_obj_t *neurosys_threebt;
    lv_obj_t *neurosys_fourbt;

    /* Page: 40 - popupcalendar */
    lv_obj_t *popupcalendar;
    lv_obj_t *popupcalendar_bg;
    lv_obj_t *popupcalendar_calendarpopup_bg;

    /* Page: 41 - popupcaution */
    lv_obj_t *popupcaution;
    lv_obj_t *popupcaution_bg;
    lv_obj_t *popupcaution_imageview1;
    lv_obj_t *popupcaution_dismissbt;

    /* Page: 44 - popupconnectionerror */
    lv_obj_t *popupconnectionerror;
    lv_obj_t *popupconnectionerror_bg;
    lv_obj_t *popupconnectionerror_popup;

    /* Page: 47 - popupdelete */
    lv_obj_t *popupdelete;
    lv_obj_t *popupdelete_bg;
    lv_obj_t *popupdelete_imageview1;
    lv_obj_t *popupdelete_yesbt;
    lv_obj_t *popupdelete_nobt;

    /* Page: 50 - popuperror */
    lv_obj_t *popuperror;
    lv_obj_t *popuperror_bg;
    lv_obj_t *popuperror_popup_dismiss;
    lv_obj_t *popuperror_imageview2;
    lv_obj_t *popuperror_e1;
    lv_obj_t *popuperror_e2;
    lv_obj_t *popuperror_e3;
    lv_obj_t *popuperror_e4;
    lv_obj_t *popuperror_e5;
    lv_obj_t *popuperror_e6;
    lv_obj_t *popuperror_e7;
    lv_obj_t *popuperror_e8;
    lv_obj_t *popuperror_e9;
    lv_obj_t *popuperror_e10;

    /* Page: 53 - popuppassword */
    lv_obj_t *popuppassword;
    lv_obj_t *popuppassword_bg;
    lv_obj_t *popuppassword_imageview1;
    lv_obj_t *popuppassword_pop_edt;
    lv_obj_t *popuppassword_pop_cautionim;
    lv_obj_t *popuppassword_pop_keypad1im;
    lv_obj_t *popuppassword_pop_keypad1;
    lv_obj_t *popuppassword_pop_keypad2im;
    lv_obj_t *popuppassword_pop_keypad2;
    lv_obj_t *popuppassword_pop_keypad3im;
    lv_obj_t *popuppassword_pop_keypad3;
    lv_obj_t *popuppassword_pop_keypad4im;
    lv_obj_t *popuppassword_pop_keypad4;
    lv_obj_t *popuppassword_pop_keypad5im;
    lv_obj_t *popuppassword_pop_keypad5;
    lv_obj_t *popuppassword_pop_keypad6im;
    lv_obj_t *popuppassword_pop_keypad6;
    lv_obj_t *popuppassword_pop_keypad7im;
    lv_obj_t *popuppassword_pop_keypad7;
    lv_obj_t *popuppassword_pop_keypad8im;
    lv_obj_t *popuppassword_pop_keypad8;
    lv_obj_t *popuppassword_pop_keypad9im;
    lv_obj_t *popuppassword_pop_keypad9;
    lv_obj_t *popuppassword_pop_keypadbackspaceim;
    lv_obj_t *popuppassword_pop_keypadbackspace;
    lv_obj_t *popuppassword_pop_keypad0im;
    lv_obj_t *popuppassword_pop_keypad0;
    lv_obj_t *popuppassword_pop_keypadalldelim;
    lv_obj_t *popuppassword_pop_keypadalldel;
    lv_obj_t *popuppassword_pop_keypadBt[12];
    lv_obj_t *popuppassword_pop_keypadim[12];




    lv_obj_t *popuppassword_pop_dismiss;
    lv_obj_t *popuppassword_pop_enter;

    /* Page: 56 - popupreset */
    lv_obj_t *popupreset;
    lv_obj_t *popupreset_bg;
    lv_obj_t *popupreset_imageview1;
    lv_obj_t *popupreset_yesbt;
    lv_obj_t *popupreset_nobt;

    /* Page: 59 - popuptime */
    lv_obj_t *popuptime;
    lv_obj_t *popuptime_bg;
    lv_obj_t *popuptime_timepopup_table;
    lv_obj_t *popuptime_settemp_setn1;
    lv_obj_t *popuptime_settemp_setn2;
    lv_obj_t *popuptime_settemp_setn3;
    lv_obj_t *popuptime_timepopup_yesbt;
    lv_obj_t *popuptime_timepopup_nobt;

    /* Page: 62 - settingmodedefrost */
    lv_obj_t *settingmodedefrost;
    lv_obj_t *settingmodedefrost_bg;
    lv_obj_t *settingmodedefrost_title;
    lv_obj_t *settingmodedefrost_backbt;
    lv_obj_t *settingmodedefrost_imageview3;

    /* Page: 65 - settingmodedegree */
    lv_obj_t *settingmodedegree;
    lv_obj_t *settingmodedegree_bg;
    lv_obj_t *settingmodedegree_title;
    lv_obj_t *settingmodedegree_backbt;
    lv_obj_t *settingmodedegree_imageview3;
    lv_obj_t *settingmodedegree_degree_c_bt;
    lv_obj_t *settingmodedegree_degree_c_im;
    lv_obj_t *settingmodedegree_degree_f_bt;
    lv_obj_t *settingmodedegree_degree_f_im;

    /* Page: 68 - settingmodedetailsetting */
    lv_obj_t *settingmodedetailsetting;
    lv_obj_t *settingmodedetailsetting_bg;
    lv_obj_t *settingmodedetailsetting_title;
    lv_obj_t *settingmodedetailsetting_backbt;
    lv_obj_t *settingmodedetailsetting_imageview3;
    lv_obj_t *settingmodedetailsetting_imageview4;
    lv_obj_t *settingmodedetailsetting_detail_temp_bt;
    lv_obj_t *settingmodedetailsetting_imageview6;
    lv_obj_t *settingmodedetailsetting_detail_humidity_bt;
    lv_obj_t *settingmodedetailsetting_imageview8;
    lv_obj_t *settingmodedetailsetting_detail_time_bt;
    lv_obj_t *settingmodedetailsetting_imageview10;
    lv_obj_t *settingmodedetailsetting_detail_damper_bt;
    lv_obj_t *settingmodedetailsetting_imageview12;
    lv_obj_t *settingmodedetailsetting_detail_defrost_bt;
    lv_obj_t *settingmodedetailsetting_imageview14;
    lv_obj_t *settingmodedetailsetting_detail_reset_bt;

    /* Page: 71 - settingmode */
    lv_obj_t *settingmode;
    lv_obj_t *settingmode_bg;
    lv_obj_t *settingmode_title;
    lv_obj_t *settingmode_setting_detailsettingbt;
    lv_obj_t *settingmode_imageview3;
    lv_obj_t *settingmode_setting_degreebt;
    lv_obj_t *settingmode_imageview5;
    lv_obj_t *settingmode_setting_recordbt;
    lv_obj_t *settingmode_imageview7;
    lv_obj_t *settingmode_setting_testbt;
    lv_obj_t *settingmode_imageview9;
    lv_obj_t *settingmode_setting_timebt;
    lv_obj_t *settingmode_imageview11;
    lv_obj_t *settingmode_setting_languagebt;
    lv_obj_t *settingmode_imageview13;
    lv_obj_t *settingmode_backbt;
    lv_obj_t *settingmode_imageview15;

    /* Page: 74 - settingmodelanguage */
    lv_obj_t *settingmodelanguage;
    lv_obj_t *settingmodelanguage_bg;
    lv_obj_t *settingmodelanguage_title;
    lv_obj_t *settingmodelanguage_backbt;
    lv_obj_t *settingmodelanguage_exitim;
    lv_obj_t *settingmodelanguage_koreanbt;
    lv_obj_t *settingmodelanguage_koreanim;
    lv_obj_t *settingmodelanguage_englishbt;
    lv_obj_t *settingmodelanguage_englishim;
    lv_obj_t *settingmodelanguage_chinabt;
    lv_obj_t *settingmodelanguage_chinaim;

    /* Page: 77 - settingmodemanual */
    lv_obj_t *settingmodemanual;
    lv_obj_t *settingmodemanual_bg;
    lv_obj_t *settingmodemanual_title;
    lv_obj_t *settingmodemanual_backbt;
    lv_obj_t *settingmodemanual_imageview3;
    lv_obj_t *settingmodemanual_setting_manual_autoim;
    lv_obj_t *settingmodemanual_setting_manual_autobt;
    lv_obj_t *settingmodemanual_setting_manual_manualim;
    lv_obj_t *settingmodemanual_setting_manual_manualbt;
    lv_obj_t *settingmodemanual_setting_manual_dryim;
    lv_obj_t *settingmodemanual_setting_manual_drybt;
    lv_obj_t *settingmodemanual_setting_manual_memoryim;
    lv_obj_t *settingmodemanual_setting_manual_memorybt;
    lv_obj_t *settingmodemanual_setting_manual_settingim;
    lv_obj_t *settingmodemanual_setting_manual_settingbt;
    lv_obj_t *settingmodemanual_setting_manual_boxim;
    lv_obj_t *settingmodemanual_setting_manual_title;
    lv_obj_t *settingmodemanual_setting_manual_value;

    /* Page: 80 - settingmoderecord */
    lv_obj_t *settingmoderecord;
    lv_obj_t *settingmoderecord_bg;
    lv_obj_t *settingmoderecord_title;
    lv_obj_t *settingmoderecord_imageview2;
    lv_obj_t *settingmoderecord_deletebt;
    lv_obj_t *settingmoderecord_backbt;
    lv_obj_t *settingmoderecord_imageview5;
    lv_obj_t *settingmoderecord_imageview6;
    lv_obj_t *settingmoderecord_chartbox0;
    lv_obj_t *settingmoderecord_chartbox1;
    lv_obj_t *settingmoderecord_chartbox2;
    lv_obj_t *settingmoderecord_chartbox3;
    lv_obj_t *settingmoderecord_chartbox4;
    lv_obj_t *settingmoderecord_imageview12;
    lv_obj_t *settingmoderecord_RecordFreezeTemp0;
    lv_obj_t *settingmoderecord_RecordFreezeTimeHour0;
    lv_obj_t *settingmoderecord_RecordFreezeTimeMin0;
    lv_obj_t *settingmoderecord_RecordDefreezeTemp0;
    lv_obj_t *settingmoderecord_RecordDefreezeTimeHour0;
    lv_obj_t *settingmoderecord_RecordDefreezeTimeMin0;
    lv_obj_t *settingmoderecord_RecordFermentation1Temp0;
    lv_obj_t *settingmoderecord_RecordFermentation1Humidity0;
    lv_obj_t *settingmoderecord_RecordFermentation1TimeHour0;
    lv_obj_t *settingmoderecord_RecordFermentation1TimeMin0;
    lv_obj_t *settingmoderecord_RecordFermentation2Temp0;
    lv_obj_t *settingmoderecord_RecordFermentation2Humidity0;
    lv_obj_t *settingmoderecord_RecordFermentation2TimeHour0;
    lv_obj_t *settingmoderecord_RecordFermentation2TimeMin0;
    lv_obj_t *settingmoderecord_RecordStartMonth0;
    lv_obj_t *settingmoderecord_RecordStartDay0;
    lv_obj_t *settingmoderecord_RecordStartHour0;
    lv_obj_t *settingmoderecord_RecordStartMin0;
    lv_obj_t *settingmoderecord_RecordEndMonth0;
    lv_obj_t *settingmoderecord_RecordEndDay0;
    lv_obj_t *settingmoderecord_RecordEndHour0;
    lv_obj_t *settingmoderecord_RecordEndMin0;
    lv_obj_t *settingmoderecord_imageview35;
    lv_obj_t *settingmoderecord_RecordFreezeTemp1;
    lv_obj_t *settingmoderecord_RecordFreezeTimeHour1;
    lv_obj_t *settingmoderecord_RecordFreezeTimeMin1;
    lv_obj_t *settingmoderecord_RecordDefreezeTemp1;
    lv_obj_t *settingmoderecord_RecordDefreezeTimeHour1;
    lv_obj_t *settingmoderecord_RecordDefreezeTimeMin1;
    lv_obj_t *settingmoderecord_RecordFermentation1Temp1;
    lv_obj_t *settingmoderecord_RecordFermentation1Humidity1;
    lv_obj_t *settingmoderecord_RecordFermentation1TimeHour1;
    lv_obj_t *settingmoderecord_RecordFermentation1TimeMin1;
    lv_obj_t *settingmoderecord_RecordFermentation2Temp1;
    lv_obj_t *settingmoderecord_RecordFermentation2Humidity1;
    lv_obj_t *settingmoderecord_RecordFermentation2TimeHour1;
    lv_obj_t *settingmoderecord_RecordFermentation2TimeMin1;
    lv_obj_t *settingmoderecord_RecordStartMonth1;
    lv_obj_t *settingmoderecord_RecordStartDay1;
    lv_obj_t *settingmoderecord_RecordStartHour1;
    lv_obj_t *settingmoderecord_RecordStartMin1;
    lv_obj_t *settingmoderecord_RecordEndMonth1;
    lv_obj_t *settingmoderecord_RecordEndDay1;
    lv_obj_t *settingmoderecord_RecordEndHour1;
    lv_obj_t *settingmoderecord_RecordEndMin1;
    lv_obj_t *settingmoderecord_imageview58;
    lv_obj_t *settingmoderecord_RecordFreezeTemp2;
    lv_obj_t *settingmoderecord_RecordFreezeTimeHour2;
    lv_obj_t *settingmoderecord_RecordFreezeTimeMin2;
    lv_obj_t *settingmoderecord_RecordDefreezeTemp2;
    lv_obj_t *settingmoderecord_RecordDefreezeTimeHour2;
    lv_obj_t *settingmoderecord_RecordDefreezeTimeMin2;
    lv_obj_t *settingmoderecord_RecordFermentation1Temp2;
    lv_obj_t *settingmoderecord_RecordFermentation1Humidity2;
    lv_obj_t *settingmoderecord_RecordFermentation1TimeHour2;
    lv_obj_t *settingmoderecord_RecordFermentation1TimeMin2;
    lv_obj_t *settingmoderecord_RecordFermentation2Temp2;
    lv_obj_t *settingmoderecord_RecordFermentation2Humidity2;
    lv_obj_t *settingmoderecord_RecordFermentation2TimeHour2;
    lv_obj_t *settingmoderecord_RecordFermentation2TimeMin2;
    lv_obj_t *settingmoderecord_RecordStartMonth2;
    lv_obj_t *settingmoderecord_RecordStartDay2;
    lv_obj_t *settingmoderecord_RecordStartHour2;
    lv_obj_t *settingmoderecord_RecordStartMin2;
    lv_obj_t *settingmoderecord_RecordEndMonth2;
    lv_obj_t *settingmoderecord_RecordEndDay2;
    lv_obj_t *settingmoderecord_RecordEndHour2;
    lv_obj_t *settingmoderecord_RecordEndMin2;
    lv_obj_t *settingmoderecord_imageview81;
    lv_obj_t *settingmoderecord_RecordFreezeTemp3;
    lv_obj_t *settingmoderecord_RecordFreezeTimeHour3;
    lv_obj_t *settingmoderecord_RecordFreezeTimeMin3;
    lv_obj_t *settingmoderecord_RecordDefreezeTemp3;
    lv_obj_t *settingmoderecord_RecordDefreezeTimeHour3;
    lv_obj_t *settingmoderecord_RecordDefreezeTimeMin3;
    lv_obj_t *settingmoderecord_RecordFermentation1Temp3;
    lv_obj_t *settingmoderecord_RecordFermentation1Humidity3;
    lv_obj_t *settingmoderecord_RecordFermentation1TimeHour3;
    lv_obj_t *settingmoderecord_RecordFermentation1TimeMin3;
    lv_obj_t *settingmoderecord_RecordFermentation2Temp3;
    lv_obj_t *settingmoderecord_RecordFermentation2Humidity3;
    lv_obj_t *settingmoderecord_RecordFermentation2TimeHour3;
    lv_obj_t *settingmoderecord_RecordFermentation2TimeMin3;
    lv_obj_t *settingmoderecord_RecordStartMonth3;
    lv_obj_t *settingmoderecord_RecordStartDay3;
    lv_obj_t *settingmoderecord_RecordStartHour3;
    lv_obj_t *settingmoderecord_RecordStartMin3;
    lv_obj_t *settingmoderecord_RecordEndMonth3;
    lv_obj_t *settingmoderecord_RecordEndDay3;
    lv_obj_t *settingmoderecord_RecordEndHour3;
    lv_obj_t *settingmoderecord_RecordEndMin3;
    lv_obj_t *settingmoderecord_imageview104;
    lv_obj_t *settingmoderecord_RecordFreezeTemp4;
    lv_obj_t *settingmoderecord_RecordFreezeTimeHour4;
    lv_obj_t *settingmoderecord_RecordFreezeTimeMin4;
    lv_obj_t *settingmoderecord_RecordDefreezeTemp4;
    lv_obj_t *settingmoderecord_RecordDefreezeTimeHour4;
    lv_obj_t *settingmoderecord_RecordDefreezeTimeMin4;
    lv_obj_t *settingmoderecord_RecordFermentation1Temp4;
    lv_obj_t *settingmoderecord_RecordFermentation1Humidity4;
    lv_obj_t *settingmoderecord_RecordFermentation1TimeHour4;
    lv_obj_t *settingmoderecord_RecordFermentation1TimeMin4;
    lv_obj_t *settingmoderecord_RecordFermentation2Temp4;
    lv_obj_t *settingmoderecord_RecordFermentation2Humidity4;
    lv_obj_t *settingmoderecord_RecordFermentation2TimeHour4;
    lv_obj_t *settingmoderecord_RecordFermentation2TimeMin4;
    lv_obj_t *settingmoderecord_RecordStartMonth4;
    lv_obj_t *settingmoderecord_RecordStartDay4;
    lv_obj_t *settingmoderecord_RecordStartHour4;
    lv_obj_t *settingmoderecord_RecordStartMin4;
    lv_obj_t *settingmoderecord_RecordEndMonth4;
    lv_obj_t *settingmoderecord_RecordEndDay4;
    lv_obj_t *settingmoderecord_RecordEndHour4;
    lv_obj_t *settingmoderecord_RecordEndMin4;

    /* Page: 83 - settingmodetest */
    lv_obj_t *settingmodetest;
    lv_obj_t *settingmodetest_bg;
    lv_obj_t *settingmodetest_title;
    lv_obj_t *settingmodetest_backbt;
    lv_obj_t *settingmodetest_imageview3;
    lv_obj_t *settingmodetest_imageview4;
    lv_obj_t *settingmodetest_compbt;
    lv_obj_t *settingmodetest_compim;
    lv_obj_t *settingmodetest_roomfanbt;
    lv_obj_t *settingmodetest_roomfanim;
    lv_obj_t *settingmodetest_fireheaterbt;
    lv_obj_t *settingmodetest_fireheaterim;
    lv_obj_t *settingmodetest_humidityheaterbt;
    lv_obj_t *settingmodetest_humidityheaterim;
    lv_obj_t *settingmodetest_watervalvebt;
    lv_obj_t *settingmodetest_watervalveim;
    lv_obj_t *settingmodetest_defrostheaterbt;
    lv_obj_t *settingmodetest_defrostheaterim;
    lv_obj_t *settingmodetest_ledbt;
    lv_obj_t *settingmodetest_ledim;
    lv_obj_t *settingmodetest_cabinetheaterbt;
    lv_obj_t *settingmodetest_cabinetheaterim;
    lv_obj_t *settingmodetest_damperbt;
    lv_obj_t *settingmodetest_damperim;
    lv_obj_t *settingmodetest_TestFreezeTemp;
    lv_obj_t *settingmodetest_TestComp;
    lv_obj_t *settingmodetest_TestHumidity;
    lv_obj_t *settingmodetest_TestDamper;
    lv_obj_t *settingmodetest_TestDcLed;
    lv_obj_t *settingmodetest_TestWaterValve;
    lv_obj_t *settingmodetest_TestDefrostHeater;
    lv_obj_t *settingmodetest_TestFireHeater;
    lv_obj_t *settingmodetest_TestHumidityHeater;
    lv_obj_t *settingmodetest_TestCabinetHeater;
    lv_obj_t *settingmodetest_TestRoomFan;
    lv_obj_t *settingmodetest_TestDefrostSensorTemp;
    lv_obj_t *settingmodetest_TestRTSensorTemp;
    lv_obj_t *settingmodetest_TestErrorCode;
    lv_obj_t *settingmodetest_test_error_check_bt;
    lv_obj_t *settingmodetest_test_error_check_im;

    /* Page: 86 - settingmodetime */
    lv_obj_t *settingmodetime;
    lv_obj_t *settingmodetime_bg;
    lv_obj_t *settingmodetime_title;
    lv_obj_t *settingmodetime_backbt;
    lv_obj_t *settingmodetime_exitim;
    lv_obj_t *settingmodetime_imageview4;
    lv_obj_t *settingmodetime_setting_time_setdate;
    lv_obj_t *settingmodetime_setting_time_setdatebt;
    lv_obj_t *settingmodetime_imageview7;
    lv_obj_t *settingmodetime_setting_time_settime;
    lv_obj_t *settingmodetime_setting_time_settimebt;

    /* settingmodetime keypad input overlay (lazy-created in settingmodetime_cb.c) */
    lv_obj_t *settingmodetime_year_txt;
    lv_obj_t *settingmodetime_month_txt;
    lv_obj_t *settingmodetime_day_txt;
    lv_obj_t *settingmodetime_hour_txt;
    lv_obj_t *settingmodetime_min_txt;
    lv_obj_t *settingmodetime_sep1_txt;    /* date "." between year/month */
    lv_obj_t *settingmodetime_sep2_txt;    /* date "." between month/day  */
    lv_obj_t *settingmodetime_tsep_txt;    /* time ":" between hour/min   */
    lv_obj_t *settingmodetime_year_ub;
    lv_obj_t *settingmodetime_month_ub;
    lv_obj_t *settingmodetime_day_ub;
    lv_obj_t *settingmodetime_hour_ub;
    lv_obj_t *settingmodetime_min_ub;
    lv_obj_t *settingmodetime_keypadbaseim;
    lv_obj_t *settingmodetime_KeyPadBt[12];
    lv_obj_t *settingmodetime_KeyPadIm[12];
    lv_obj_t *settingmodetime_keypadhide;
    lv_obj_t *settingmodetime_keypadhide_im;
    lv_obj_t *settingmodetime_daterow_ub;   /* green underbar below date row (선택 표시) */
    lv_obj_t *settingmodetime_timerow_ub;   /* green underbar below time row (선택 표시) */
    lv_obj_t *settingmodetime_ampm_txt;     /* "AM"/"PM" label in time edit mode        */
    lv_obj_t *settingmodetime_ampm_bt;      /* tappable AM/PM toggle button              */

    /* Page: 89 - timebar */
    lv_obj_t *timebar;
    lv_obj_t *timebar_timebar_bg;
    lv_obj_t *timebar_timebar_error_checkim;
    lv_obj_t *timebar_timebar_error_checkbt;
    lv_obj_t *timebar_comp_checkim;
    lv_obj_t *timebar_watervalve_checkim;
    lv_obj_t *timebar_roomfan_checkim;
    lv_obj_t *timebar_damper_checkim;
    lv_obj_t *timebar_humid_checkim;
    lv_obj_t *timebar_heat_checkim;
    lv_obj_t *timebar_defrost_checkim;
    lv_obj_t *timebar_sound_checkim;
    lv_obj_t *timebar_sound_checkbt;
    lv_obj_t *timebar_timebar_timetxt;
    lv_obj_t *timebar_timebar_datetxt;

} bk_lv_ui_t;

/* Page init / destroy declarations */
void init_page_activitymain(bk_lv_ui_t *bk_ui);
void destroy_page_activitymain(bk_lv_ui_t *bk_ui);
void init_page_autodrymode(bk_lv_ui_t *bk_ui);
void destroy_page_autodrymode(bk_lv_ui_t *bk_ui);
void init_page_automodeend(bk_lv_ui_t *bk_ui);
void destroy_page_automodeend(bk_lv_ui_t *bk_ui);
void init_page_automode(bk_lv_ui_t *bk_ui);
void destroy_page_automode(bk_lv_ui_t *bk_ui);
void init_page_automodestart(bk_lv_ui_t *bk_ui);
void destroy_page_automodestart(bk_lv_ui_t *bk_ui);
void init_page_detailsettingdamper(bk_lv_ui_t *bk_ui);
void destroy_page_detailsettingdamper(bk_lv_ui_t *bk_ui);
void init_page_detailsettingdefrost(bk_lv_ui_t *bk_ui);
void destroy_page_detailsettingdefrost(bk_lv_ui_t *bk_ui);
void init_page_detailsettinghumidity(bk_lv_ui_t *bk_ui);
void destroy_page_detailsettinghumidity(bk_lv_ui_t *bk_ui);
void init_page_detailsettingtemp(bk_lv_ui_t *bk_ui);
void destroy_page_detailsettingtemp(bk_lv_ui_t *bk_ui);
void init_page_detailsettingtime(bk_lv_ui_t *bk_ui);
void destroy_page_detailsettingtime(bk_lv_ui_t *bk_ui);
void init_page_introactivity(bk_lv_ui_t *bk_ui);
void destroy_page_introactivity(bk_lv_ui_t *bk_ui);
void init_page_main(bk_lv_ui_t *bk_ui);
void destroy_page_main(bk_lv_ui_t *bk_ui);
void init_page_manualmode(bk_lv_ui_t *bk_ui);
void destroy_page_manualmode(bk_lv_ui_t *bk_ui);
void init_page_manualmodestart(bk_lv_ui_t *bk_ui);
void destroy_page_manualmodestart(bk_lv_ui_t *bk_ui);
void init_page_memorymode(bk_lv_ui_t *bk_ui);
void destroy_page_memorymode(bk_lv_ui_t *bk_ui);
void init_page_neurosys(bk_lv_ui_t *bk_ui);
void destroy_page_neurosys(bk_lv_ui_t *bk_ui);
void init_page_popupcalendar(bk_lv_ui_t *bk_ui);
void destroy_page_popupcalendar(bk_lv_ui_t *bk_ui);
void init_page_popupcaution(bk_lv_ui_t *bk_ui);
void destroy_page_popupcaution(bk_lv_ui_t *bk_ui);
void init_page_popupconnectionerror(bk_lv_ui_t *bk_ui);
void destroy_page_popupconnectionerror(bk_lv_ui_t *bk_ui);
void init_page_popupdelete(bk_lv_ui_t *bk_ui);
void destroy_page_popupdelete(bk_lv_ui_t *bk_ui);
void init_page_popuperror(bk_lv_ui_t *bk_ui);
void destroy_page_popuperror(bk_lv_ui_t *bk_ui);
void init_page_popuppassword(bk_lv_ui_t *bk_ui);
void destroy_page_popuppassword(bk_lv_ui_t *bk_ui);
/* password_popup.png를 canvas 버퍼에 1회 decode (settingmode SCREEN_LOADED에서 호출) */
void popuppassword_bg_preload(void);
/* canvas + buf 반납 651 KB (settingmode SCREEN_UNLOAD_START에서 호출) */
void popuppassword_canvas_free(void);
#if UI_POPUPPASSWORD_COMBINED_BG_ENABLE
/* init_page_popuppassword()가 lv_scr_load()로 팝업 화면을 여는 그 순간(1)인지 —
 * settingmode SCREEN_UNLOAD_START가 이 때 동기적으로 같이 발생하므로,
 * "팝업을 여는 중"과 "settingmode를 완전히 떠남"을 구분하는 데 씀. */
int popuppassword_is_screen_opening(void);
#endif
#if UI_POPUPPASSWORD_KEYPAD_COMBINED_ENABLE
/* 키패드 12장을 canvas 스프라이트시트로 1회 decode (settingmode SCREEN_LOADED에서 호출) */
void popuppassword_keypad_preload(void);
/* 키패드 canvas + buf 반납 (settingmode SCREEN_UNLOAD_START에서 호출) */
void popuppassword_keypad_canvas_free(void);
#endif
void init_page_popupreset(bk_lv_ui_t *bk_ui);
void destroy_page_popupreset(bk_lv_ui_t *bk_ui);
/* reset_popup*.png(알파 있는 RGBA)을 전용 ARGB8888 canvas에 1회 decode —
 * settingmodedetailsetting_cb.c의 _rst_prewarm_tick()에서 호출 */
void popupreset_bg_preload(void);
/* canvas 위젯만 정리(버퍼는 유지) — settingmodedetailsetting SCREEN_UNLOAD_START에서 호출 */
void popupreset_canvas_free(void);
/* 728KB 버퍼를 부팅 극초반(단편화 전)에 선점 — main_activity_on_create()에서 1회 호출 */
void popupreset_canvas_buf_alloc(void);
void automodestart_canvas_buf_alloc(void);
void settingmodetest_canvas_buf_alloc(void);
void init_page_popuptime(bk_lv_ui_t *bk_ui);
void destroy_page_popuptime(bk_lv_ui_t *bk_ui);
void init_page_settingmodedefrost(bk_lv_ui_t *bk_ui);
void destroy_page_settingmodedefrost(bk_lv_ui_t *bk_ui);
void init_page_settingmodedegree(bk_lv_ui_t *bk_ui);
void destroy_page_settingmodedegree(bk_lv_ui_t *bk_ui);
void init_page_settingmodedetailsetting(bk_lv_ui_t *bk_ui);
void destroy_page_settingmodedetailsetting(bk_lv_ui_t *bk_ui);
void init_page_settingmode(bk_lv_ui_t *bk_ui);
void destroy_page_settingmode(bk_lv_ui_t *bk_ui);
void init_page_settingmodelanguage(bk_lv_ui_t *bk_ui);
void destroy_page_settingmodelanguage(bk_lv_ui_t *bk_ui);
void init_page_settingmodemanual(bk_lv_ui_t *bk_ui);
void destroy_page_settingmodemanual(bk_lv_ui_t *bk_ui);
void init_page_settingmoderecord(bk_lv_ui_t *bk_ui);
void destroy_page_settingmoderecord(bk_lv_ui_t *bk_ui);
void init_page_settingmodetest(bk_lv_ui_t *bk_ui);
void destroy_page_settingmodetest(bk_lv_ui_t *bk_ui);
/* testmode_box.jpg를 전용 canvas 버퍼에 1회 decode (settingmode SCREEN_LOADED에서 호출) */
void settingmodetest_bg_preload(void);
/* canvas + buf 반납 ~832 KB (settingmode SCREEN_UNLOAD_START에서 호출) */
void settingmodetest_canvas_free(void);
/* canvas를 보장(필요시 재decode)하고 settingmodetest_imageview4의 src를
 * 다시 맞춤 — settingmodetest_cb.c의 SCREEN_LOAD_START(매 진입)에서 호출 */
void settingmodetest_apply_bg(bk_lv_ui_t *bk_ui);
void init_page_settingmodetime(bk_lv_ui_t *bk_ui);
void destroy_page_settingmodetime(bk_lv_ui_t *bk_ui);
void settingmodetime_keypad_event_cb(lv_event_t *e);
void settingmodetime_keypadhide_event_cb(lv_event_t *e);
void settingmodetime_ampm_bt_event_cb(lv_event_t *e);
void settingmodetime_field_tap_event_cb(lv_event_t *e);
void init_page_timebar(bk_lv_ui_t *bk_ui);
void destroy_page_timebar(bk_lv_ui_t *bk_ui);

#ifdef __cplusplus
}
#endif

#endif /* __BEKEN_UI_H__ */
