/*
 * Copyright (c) 2025 BekenCorp. All rights reserved.
 * 
 * This software is proprietary and confidential. No part of this software may be
 * reproduced, distributed, or transmitted in any form or by any means, including
 * photocopying, recording, or other electronic or mechanical methods, without the
 * prior written permission of BekenCorp, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted
 * by copyright law.
 * 
 * For permission requests, write to BekenCorp at armino_support@bekencorp.com.

 * Author: Beken LVGL Designer Tool
*/
/**
 * @file custom_func.h
 * @brief Custom Function Declarations
 * 
 * This file contains declarations for custom functions used in event handlers.
 * Generated by Beken LVGL Designer Tool.
 * 
 * Note: Function implementations are in custom_func.c
 */

#ifndef __CUSTOM_FUNC_H__
#define __CUSTOM_FUNC_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "beken_ui.h"
#include "event_runtime.h"
#include "ui_config.h"

// add custom functions here
void ui_page_build_set_image_src(lv_obj_t *obj, const void *src);
void ui_page_build_enqueue_task(void (*task)(void), const char *name);

#if UI_IMG_TIMED_ENABLE
/* [IMGTIME] 로그 출력 래퍼. 비활성화해도 page-build capture는 유지됨. */
void _img_set_src_timed(lv_obj_t *obj, const void *src);
#else
#define _img_set_src_timed(obj, src)  ui_page_build_set_image_src((obj), (src))
#endif

/* Deferred image loading — stores src path without loading.
 * Call _img_ensure_src() before first show. */
void _img_set_src_deferred(lv_obj_t *obj, const char *src);

#if !UI_BG_SOLID_COLOR && UI_BG_CANVAS_PRELOAD_ENABLE
/* bg.jpg 공유 canvas 영구 버퍼.
 * bg_canvas_buf_alloc: main_activity_on_create에서만 호출 (단순 lv_malloc, LVGL task 불필요)
 * bg_canvas_preload:   _bg_set 내부에서 첫 호출 시 canvas 생성 + JPEG decode (idempotent) */
void bg_canvas_buf_alloc(void);
void bg_canvas_preload(void);
const lv_image_dsc_t *bg_canvas_get_dsc(void);
#endif

/* bg 배경 설정 매크로.
 * UI_BG_SOLID_COLOR=1: bg lv_image 숨기고 parent screen에 단색 채움
 * UI_BG_SOLID_COLOR=0, UI_BG_CANVAS_PRELOAD_ENABLE=1: 부팅 시 canvas 지연 decode 후 dsc 재사용
 * UI_BG_SOLID_COLOR=0, UI_BG_CANVAS_PRELOAD_ENABLE=0: 화면 진입마다 /images/bg.jpg 직접 디코딩 */
#if UI_BG_SOLID_COLOR
#  define _bg_set(obj) do { \
    lv_obj_add_flag((obj), LV_OBJ_FLAG_HIDDEN); \
    lv_obj_set_style_bg_color(lv_obj_get_parent(obj), lv_color_hex(UI_BG_COLOR_HEX), 0); \
    lv_obj_set_style_bg_opa(lv_obj_get_parent(obj), LV_OPA_COVER, 0); \
} while(0)
#elif UI_BG_CANVAS_PRELOAD_ENABLE
#  define _bg_set(obj) do { \
    bg_canvas_preload(); \
    const lv_image_dsc_t *_dsc = bg_canvas_get_dsc(); \
    if (_dsc) lv_image_set_src((obj), _dsc); \
    else      _img_set_src_timed((obj), "/images/bg.jpg"); \
} while(0)
#else
#  define _bg_set(obj) _img_set_src_timed((obj), "/images/bg.jpg")
#endif

/* Load image src if not yet loaded (deferred objects only). Safe to call on
 * any lv_obj_t — returns immediately for non-image or already-loaded objects. */
void _img_ensure_src(lv_obj_t *obj);

/* PSRAM 여유가 UI_CACHE_DROP_LOW_MEM_THRESHOLD_BYTES 미만이면(쿨다운 지나면)
 * 공유 이미지 캐시(lv_image_cache_drop(NULL))를 즉시 비움 — 위험한 decode
 * 호출 직전에 불러 단편화로 인한 malloc 실패 확률을 낮추는 용도.
 * 여러 호출자가 같은 쿨다운을 공유하므로 어디서 불러도 중복 발동 안 함. */
void ui_cache_drop_if_low_mem(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /* __CUSTOM_FUNC_H__ */

