/* device_state.h — C equivalent of MainActivity shared state
 * Auto-generated by android2lvgl. Modify as needed for Beken7258 target.
 */
#ifndef __DEVICE_STATE_H__
#define __DEVICE_STATE_H__

#include <stdint.h>
#include <stdbool.h>

/* Edit target IDs (testcontrolint equivalents) */
#define EDIT_NONE                    0
#define EDIT_FREEZE_TEMP             1
#define EDIT_DEFROST_TEMP            2
#define EDIT_DEFROST_HUMIDITY        3
#define EDIT_DEFROST_TIME_HOUR       4
#define EDIT_DEFROST_TIME_MIN        5
#define EDIT_FERM1_TEMP              6
#define EDIT_FERM1_HUMIDITY          7
#define EDIT_FERM1_TIME_HOUR         8
#define EDIT_FERM1_TIME_MIN          9
#define EDIT_FERM2_TEMP              10
#define EDIT_FERM2_HUMIDITY          11
#define EDIT_FERM2_TIME_HOUR         12
#define EDIT_FERM2_TIME_MIN          13
#define EDIT_COMPLETE_YEAR           14
#define EDIT_COMPLETE_MONTH          15
#define EDIT_COMPLETE_DAY            16
#define EDIT_COMPLETE_HOUR           17
#define EDIT_COMPLETE_MIN            18

/* UI test mode: 1 = each auto-mode stage forced to AUTO_MODE_TEST_MIN minutes.
 * Set to 0 before release. */
#define AUTO_MODE_TEST               0
#define AUTO_MODE_TEST_MIN           1

/* Operation mode codes (saveoperation[current]) */
#define OP_MODE_FREEZE               0
#define OP_MODE_DEFROST              1
#define OP_MODE_FERM1                2
#define OP_MODE_FERM2                3
#define OP_MODE_DRY                  4

/* Language codes */
#define LANG_KOREAN                  0
#define LANG_CHINESE                 1
#define LANG_ENGLISH                 2

/* Memory mode check values */
#define MEMORY_MODE_NONE             0
#define MEMORY_MODE_SAVE             1
#define MEMORY_MODE_LOAD             2

/* Manual mode */
#define MANUAL_MODE_FREEZE           1
#define MANUAL_MODE_DEFROST          2
#define MANUAL_MODE_FERM             3
#define MANUAL_MODE_FERM2            4  /* 저온발효 표시 (과발효방지 AutoModeOver — fermentation_bg, 자동설정 타이틀) */

#define MEMORY_SLOTS                 12
#define MEMORY_ITEMS                 18

/* HW test output control bits (sent via 0x50) */
#define HW_TEST_COMP            0
#define HW_TEST_FAN             1
#define HW_TEST_FIRE_HEATER     2
#define HW_TEST_HUMID_HEATER    3
#define HW_TEST_WATER_VALVE     4
#define HW_TEST_DEFROST_HEATER  5
#define HW_TEST_DC_LED          6
#define HW_TEST_CABINET_HEATER  7
#define HW_TEST_DAMPER          8

/* 0x60 HW test response — named fields */
typedef struct {
    int8_t  f_temp;            /* F sensor temperature */
    int8_t  defrost_temp;      /* defrost sensor temperature */
    uint8_t humidity;          /* humidity % */
    int8_t  rt_temp;           /* RT sensor temperature */
    uint8_t error_code;        /* sensor error bits (same as Error Code 1 in 0x43) */
    uint8_t comp;
    uint8_t fan;
    uint8_t fire_heater;
    uint8_t humid_heater;
    uint8_t water_valve;
    uint8_t defrost_heater;
    uint8_t dc_led;
    uint8_t cabinet_heater;
    uint8_t damper;
} hw_test_result_t;

typedef struct {
    /* --- Operation flags --- */
    bool operation;
    bool auto_mode;
    bool auto_mode_start;
    bool auto_dry_mode_start;
    bool auto_dry_complete;    /* MCU 0x52 또는 wall clock 완료 → 완료 부저/화면 전환용 */
    bool manual_start;
    bool test_mode;
    bool change_setting;
    bool first_start;
    bool first_freeze;
    bool first_defrost;
    bool first_send;
    bool drive_check;
    bool error_popup;
    bool black_out_checking;
    bool save_writing;

    /* --- Lock / sound --- */
    bool lock;
    bool hard_lock;
    bool mute;

    /* --- UI / screen state --- */
    int  degree;               /* 0=°C  1=°F */
    int  language;             /* LANG_* */
    int  manual_current_mode;  /* MANUAL_MODE_* */
    int  day_period;           /* 0=manual,1=same day,2=next day,3-8=holiday */
    int  memory_mode_check;    /* MEMORY_MODE_* */

    /* --- Communication flags --- */
    bool start_run;
    bool start_run1;
    bool start_run2;
    int  comm_error_count;
    bool error_cut;

    /* --- Send parameter buffer (for 0x30/0x31 packets) --- */
    int  send_freeze_temp;
    int  send_freeze_hour;
    int  send_freeze_min;
    int  send_defreeze_temp;
    int  send_defreeze_humidity;
    int  send_defreeze_hour;
    int  send_defreeze_min;
    int  send_ferm1_temp;
    int  send_ferm1_humidity;
    int  send_ferm1_hour;
    int  send_ferm1_min;
    int  send_ferm2_temp;
    int  send_ferm2_humidity;
    int  send_ferm2_hour;
    int  send_ferm2_min;
    int  send_dry_temp;
    int  send_dry_humidity;
    int  send_dry_hour;
    int  send_dry_min;
    int  send_complete_year;
    int  send_complete_month;
    int  send_complete_day;
    int  send_complete_hour;
    int  send_complete_min;
    int  send_complete_sec;
    int  send_start_year;
    int  send_start_month;
    int  send_start_day;
    int  send_start_hour;
    int  send_start_min;
    int  first_operator_mode;  /* 0x10=freeze, 0x20=defrost, 0x50=dry */
    bool over_ferm_active;       /* 과발효방지 대기 중 (MCU 0x34 전환까지) */
    bool over_ferm_jeon_started; /* MCU 0x34 수신: automodeend→manualmodestart 전환 신호 */
    bool auto_mode_over;         /* 과발효방지 저온발효 중 (Android AutoModeOver 동일) */
    bool first_receive;
    int  lamp;                 /* interior lamp on/off */
    int  send_save_value1[32]; /* mirror of SaveValue1 received via 0x20, re-sent in 0x30 */
    int  savetesttest[16];     /* hw test output bits sent via 0x50 */

    /* --- Received sensor data (from 0x43 packet) --- */
    int     saveoperation[16];   /* raw status array from device */
    int     current_op_mode;     /* OP_MODE_* */
    int     current_temp;        /* signed °C from MCU */
    int     current_humidity;    /* % */
    int     remain_hour;
    int     remain_min;
    int     elapsed_hour;   /* saveoperation[12]: MCU 실제 경과시간 h */
    int     elapsed_min;    /* saveoperation[13]: MCU 실제 경과시간 m */
    /* 정전 복구 arc: 원래 행정 전체 시간(분). _total_min_for_mode가 잔여분 대신 사용.
     * 복구 진입 시 한 번만 설정, black_out_checking 중에만 참조. */
    int     bo_freeze_total_min;
    int     bo_defrost_total_min;
    int     bo_ferm1_total_min;
    int     bo_ferm2_total_min;
    uint8_t error_flags[4];
    uint8_t mcu_version;         /* MCU firmware version (0x20 byte 23) */
    int     lamp_from_mcu;       /* interior lamp state reported by MCU (0x43 byte 3) */

    /* --- Timebar icon flags (from 0x43 saveoperation[6],[7]) --- */
    bool op_comp;           /* saveoperation[6] bit0 — 컴프레셔 */
    bool op_fire_heater;    /* saveoperation[6] bit1 — 파이어히터 */
    bool op_humid_heater;   /* saveoperation[6] bit2 — 습도히터 */
    bool op_water_pump;     /* saveoperation[6] bit3 — 워터밸브 */
    bool op_fan;            /* saveoperation[6] bit4 — 룸팬 */
    bool op_frozen_heater;  /* saveoperation[6] bit6 — 제상히터 */
    bool op_damper;         /* saveoperation[7] bit0 — 댐퍼 */
    bool op_error;          /* saveoperation[8],[9] 에러비트 */

    /* --- Hardware test results (from 0x60 packet) --- */
    hw_test_result_t hw_test;
    bool    testing;
    bool    testreceive;

    /* --- Keypad edit state --- */
    bool edit_mode;
    int  edit_target;            /* EDIT_* */
    char edit_buffer[16];

    /* --- Memory load buffer (15 items) --- */
    char memory_auto_load[MEMORY_ITEMS][16];
    char memory_auto_save[MEMORY_ITEMS][16];

    /* --- Memory slot selection (shared by all language variants) --- */
    int  memory_slot_page;      /* 0-2 */
    int  memory_slot_checking;  /* 1-4 */

} device_state_t;

extern device_state_t g_device_state;

void device_state_init(void);

#endif /* __DEVICE_STATE_H__ */
