/* settings.h — C equivalent of SettingData.kt (87 settings → NVS/Flash)
 * Auto-generated by android2lvgl.
 */
#ifndef __SETTINGS_H__
#define __SETTINGS_H__

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#define SETTINGS_COUNT  175   /* total entries including Memory/Record slots */

typedef struct {
    const char *key;
    char        value[32];
    const char *default_value;
    uint8_t     dirty;   /* 1 = changed since last save */
} setting_entry_t;

/* Lifecycle */
void        settings_init(void);
void        settings_load_from_flash(void); /* call from background after WiFi cal (~35s) */
int         settings_is_loaded(void);       /* 1 after load_from_flash completes */
void        settings_save_all(void);       /* mark all dirty and save */
void        settings_save_dirty(void);     /* save only changed entries (deferred) */
void        settings_save_all_sync(void);  /* save_all + immediate flash write */
void        settings_flush(void);          /* write deferred saves to flash (call from bg thread) */
void        settings_factory_reset(void);  /* reset to Android defaults, rewrite blob */

/* Read */
const char *settings_get_str(const char *key);
int         settings_get_int(const char *key);
float       settings_get_float(const char *key);

/* Write */
void        settings_set_str(const char *key, const char *value);
void        settings_set_int(const char *key, int value);
void        settings_set_float(const char *key, float value);

/* Bulk copy helpers for memory/record slots */
void        settings_copy(const char *dst_key, const char *src_key);

#ifdef __cplusplus
}
#endif
#endif /* __SETTINGS_H__ */
