/*
 * Copyright (c) 2025 BekenCorp. All rights reserved.
 * 
 * This software is proprietary and confidential. No part of this software may be
 * reproduced, distributed, or transmitted in any form or by any means, including
 * photocopying, recording, or other electronic or mechanical methods, without the
 * prior written permission of BekenCorp, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted
 * by copyright law.
 * 
 * For permission requests, write to BekenCorp at armino_support@bekencorp.com.

 * Author: Beken LVGL Designer Tool
*/
/**
 * @file custom_func.c
 * @brief Custom Function Implementations
 * 
 * This file contains implementations for custom functions used in event handlers.
 * Generated by Beken LVGL Designer Tool.
 * 
 * Users should implement the function bodies according to their requirements.
 */

#include "custom_func.h"
#include "beken_ui.h"
#include "event_runtime.h"
#include "preRenderer.h"
#include <stdio.h>

#define TAG "[custom_func.c] "
#define bk_printf(fmt, ...) do {if(0) printf(fmt, ##__VA_ARGS__); } while(0) // disable printf

void _img_set_src_timed(lv_obj_t *obj, const void *src)
{
    uint32_t t = lv_tick_get();
    ui_page_build_set_image_src(obj, src);
// ?#ifdef HAL_USE_EMULATOR
    // lv_delay_ms(20);
    
    // _img_set_src_timed(obj, path);
    uint32_t ms = lv_tick_elaps(t);
    const char *srcName = lv_image_src_get_type(src) == LV_IMAGE_SRC_FILE
                        ? (const char *)src : "<variable>";
    bk_printf(TAG "[IMGTIME] %-52s %4lu ms\n",
              srcName, (unsigned long)ms);
// ?#endif
}

void _img_set_src_deferred(lv_obj_t *obj, const char *src)
{
    if (!obj) return;
    lv_obj_set_user_data(obj, (void *)src);
}

void _img_ensure_src(lv_obj_t *obj)
{
    // uint32_t t = lv_tick_get();
    if (!obj || !lv_obj_is_valid(obj)) return;
    if (!lv_obj_check_type(obj, &lv_image_class)) return;
    if (lv_image_get_src(obj) != NULL) return;
    const char *src = (const char *)lv_obj_get_user_data(obj);
    if (src) ui_page_build_set_image_src(obj, src);
    // uint32_t ms = lv_tick_elaps(t);
    // printf("[IMGTIME1] %-52s %4lu ms\n", src, ms);
}


