/*
 * Copyright (c) 2025 BekenCorp. All rights reserved.
 * 
 * This software is proprietary and confidential. No part of this software may be
 * reproduced, distributed, or transmitted in any form or by any means, including
 * photocopying, recording, or other electronic or mechanical methods, without the
 * prior written permission of BekenCorp, except in the case of brief quotations
 * embodied in critical reviews and certain other noncommercial uses permitted
 * by copyright law.
 * 
 * For permission requests, write to BekenCorp at armino_support@bekencorp.com.

 * Author: Beken LVGL Designer Tool
*/
/**
 * @file custom_func.h
 * @brief Custom Function Declarations
 * 
 * This file contains declarations for custom functions used in event handlers.
 * Generated by Beken LVGL Designer Tool.
 * 
 * Note: Function implementations are in custom_func.c
 */

#ifndef __CUSTOM_FUNC_H__
#define __CUSTOM_FUNC_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "beken_ui.h"
#include "event_runtime.h"

// add custom functions here
void _img_set_src_timed(lv_obj_t *obj, const void *src);
/* Deferred image loading — stores src path without loading.
 * Call _img_ensure_src() before first show. */
void _img_set_src_deferred(lv_obj_t *obj, const char *src);

/* Load image src if not yet loaded (deferred objects only). Safe to call on
 * any lv_obj_t — returns immediately for non-image or already-loaded objects. */
void _img_ensure_src(lv_obj_t *obj);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /* __CUSTOM_FUNC_H__ */

